---
- Server Tools:
    - Docker Hub:
        - abbr: DH
          href: https://hub.docker.com
    - Homepage Docs:
        - abbr: HP
          href: https://gethomepage.dev
    - Ubuntu Packages:
        - abbr: APT
          href: https://packages.ubuntu.com

- Developer:
    - GitHub:
        - abbr: GH
          href: https://github.com/Shaneeen
    - MDN Web Docs:
        - abbr: MDN
          href: https://developer.mozilla.org
