---
title: lanceenbox
description: matcha strawberry server dashboard
theme: dark
color: rose
headerStyle: boxed
hideVersion: true
iconStyle: theme
statusStyle: dot
target: _blank
useEqualHeights: true

layout:
  Control Room:
    style: row
    columns: 4
  Network & Access:
    style: row
    columns: 4
  Files & Projects:
    style: row
    columns: 4
  Health Checks:
    style: row
    columns: 4
  Launch Pad:
    style: row
    columns: 4
